.PHONY: clean All

All:
	@echo "----------Building project:[ carpetCleaningService - Debug ]----------"
	@cd "carpetCleaningService" && "$(MAKE)" -f  "carpetCleaningService.mk"
clean:
	@echo "----------Cleaning project:[ carpetCleaningService - Debug ]----------"
	@cd "carpetCleaningService" && "$(MAKE)" -f  "carpetCleaningService.mk" clean
