.PHONY: clean All

All:
	@echo "----------Building project:[ vectors - Debug ]----------"
	@cd "vectors" && "$(MAKE)" -f  "vectors.mk"
clean:
	@echo "----------Cleaning project:[ vectors - Debug ]----------"
	@cd "vectors" && "$(MAKE)" -f  "vectors.mk" clean
